### ISSUE TITLE
Image manipulation suggestions

### ISSUE THREAD

**Issue by FionaMacNeill** [mrbracchi/Awesome-ID#1]
**[Kraken.io](https://kraken.io/web-interface)** 
Quick image optimization for web tool. Helpful to ensure that your images do not slow down load times in learning object tools such as Articulate Rise and H5P. 

**[ImageOptim for Mac](https://imageoptim.com/mac)** 
Excellent FREE open source utility for web optimization of multiple images at a time. Locally installed so no issues with transferring proprietary images to a web-based tool.

**Comment by mrbracchi** [comment]
Added and merged
