### ISSUE TITLE
Closed Captions and subtitles

### ISSUE THREAD

**Issue by FionaMacNeill** [mrbracchi/Awesome-ID#2]
**[SRT to VTT converter](https://github.com/silviapfeiffer/silviapfeiffer.github.io)** 
Excellent converter for SRT (the subtitle file type that Camtasia and some other tools put out) to VTT, the format required by Microsoft Stream, SharePoint and others. Create your own HTML file including the source code to run this locally on your computer. 

**[Understand Subtitles](https://www.bbc.com/academy-guides/how-do-i-create-subtitles)** 
This fantastic guide from the BBC explains the different types of subtitles, including closed captions and open captions. It provides visual examples and explains the different file types.

**Comment by mrbracchi** [comment]
Added and merged.
