### ISSUE TITLE
Color Tools

### ISSUE THREAD

**Issue by FionaMacNeill** [mrbracchi/Awesome-ID#4]
**[Adobe Color](https://color.adobe.com/)** 
Free web tool for creating color schemes using a colour wheel with built-in color theory. Now includes a contrast checker. 

**Firefox Eyedropper** 
Sample the HEX code for any element you find on the web (in a photo, in a web design, etc.). Select the hamburger menu on the top-right of Firefox. Then select More tools to use the Eyedropper.

**[Who Can Use?](https://whocanuse.com/)** 
Make sure that your colour choices will perform well for all users. Including those with colour perspection differences, certain visual impairments and also in different lighting conditions.

**Comment by mrbracchi** [comment]
Where do you see this best fitting in? I am thinking under Misc- Software. Perhaps the "Who can use" would go in accessibility.

**Comment by FionaMacNeill** [comment]
Adobe Color and Firefox Eyedropper are probably design tools/utilities, but Misc is okay. 

Who Can Use? Can go under Accessibility indeed.

**Comment by mrbracchi** [comment]
Merged into project
